# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
r_github_packages:
  - r-lib/covr
os:
  - linux
r:
  - release
  - devel
env:
  - COMPILER_VER=5
matrix:
  fast_finish: true
  include:
    - os: osx
      r: release
      sudo: required
  allow_failures:
    - os: osx
# see http://thecoatlessprofessor.com/programming/r/selecting-an-alternative-compiler-for-r-package-testing-on-travis-ci/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      sudo tlmgr install placeins cleveref
    else
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 50
    fi
after_success:
  - if [[ ("$TRAVIS_R_VERSION" != "devel") && ("$TRAVIS_OS_NAME" == "linux") ]]; then
      travis_wait 30 Rscript codecov.R
    fi
notifications:
  email:
    on_success: change
    on_failure: change
