# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
- tlmgr install amsmath subcaption placeins makecell

os:
- linux
- osx
r:
- release
- devel
