# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

os:
- linux
- osx
r:
- release
- devel

before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then tlmgr install placeins; fi
