# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_build_args: "--compact-vignettes"

r_packages:
  - covr

sudo:
  - false
os:
  - linux
r:
  - release
  - devel

matrix:
  include:
    - os: osx
      r: release
      sudo: required

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install placeins cleveref; fi

after_success:
  - if [[ ("$TRAVIS_R_VERSION" != "devel") && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'library(covr); codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
